export const categories: Record<string, string[]> = {
  "Mechanic & Repair": [
    "Diagnostics",
    "Engine repair",
    "Transmission",
    "Brakes",
    "Oil changes",
    "Cooling systems",
    "AC repair",
  ],
  "Bodywork & Collision": [
    "Collision repair",
    "Dent removal",
    "Paintless dent repair",
    "Rust repair",
    "Panel replacement",
  ],
  "Suspension & Steering": [
    "Lift kits",
    "Lowering kits",
    "Coilovers",
    "Air suspension",
    "Shocks & struts",
    "Wheel alignment",
  ],
  "Motorcycle Shop": [
    "Motorcycle repair",
    "Motorcycle tires",
    "Motorcycle suspension",
    "Motorcycle customization",
  ],
  "Wheels & Tires": [
    "Tire installation",
    "Balancing",
    "Tire repair",
    "Wheel repair",
    "Custom wheels",
  ],
  "Paint & Wraps": [
    "Full paint",
    "Custom paint",
    "Vinyl wraps",
    "Paint protection film",
  ],
  "Performance & Tuning": [
    "ECU tuning",
    "Dyno tuning",
    "Turbo installation",
    "Exhaust",
    "Engine builds",
  ],
  "Truck & Off-Road": [
    "4×4 upgrades",
    "Off-road suspension",
    "Truck accessories",
    "Bumpers",
    "Winches",
  ],
  "Detailing & Protection": [
    "Interior detailing",
    "Paint correction",
    "Ceramic coating",
    "Window tint",
  ],
  "Electrical & Audio": [
    "Electrical diagnostics",
    "Wiring",
    "Lighting",
    "Audio installation",
    "Alarms",
  ],
  "Fabrication & Restoration": [
    "Welding",
    "Custom fabrication",
    "Classic restoration",
    "Upholstery",
  ],
};
export const vehicles = ["Car", "Truck", "Motorcycle"];
