'use client';
import {useEffect,useState} from 'react';
import PhotoPicker from './PhotoPicker';
import {supabase} from '@/lib/supabase';
async function headers(){const {data:{session}}=await supabase.auth.getSession();return {'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`};}
export function ContactShop({shopId}:{shopId:string}){
 const [files,F]=useState<File[]>([]);
 const [kind,K]=useState('quote'),[body,B]=useState(''),[email,E]=useState(''),[message,M]=useState(''),[busy,S]=useState(false);
 return <section className="form-card"><h2>Contact this shop</h2><p>Quote requests go to this shop’s DGD inbox. Reports go to DGD for review. Sign in before sending.</p><a href={`/login?next=${encodeURIComponent(`/shop-finder/shops/${shopId}`)}`}>Sign in to DGD</a><form onSubmit={async e=>{e.preventDefault();S(true);M('');try{const photos=kind==='quote'?await Promise.all(files.map(f=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Could not read photo'));reader.readAsDataURL(f);} ))):[];const r=await fetch('/api/shop-finder/messages' ,{method:'POST',headers:await headers(),body:JSON.stringify({shopId,kind,body,email,photos})});const d=await r.json();M(d.message||d.error);if(r.ok){B('');F([]);}}catch{M('Could not send. Please try again.');}finally{S(false);}}}><label className="field">Message type<select value={kind} onChange={e=>K(e.target.value)}><option value="quote">Request a quote</option><option value="report">Report this listing</option></select></label><label className="field">Reply email<input type="email" required maxLength={254} value={email} onChange={e=>E(e.target.value)}/></label><label className="field">{kind==='quote'?'Vehicle year, make, model, and work needed':'What information is wrong?'}<textarea required minLength={10} maxLength={3000} value={body} onChange={e=>B(e.target.value)}/></label>{kind==='quote'&&<PhotoPicker files={files} onChange={F} maximum={2} label="Project photos (optional)" onError={M}/>}<p className="small">Your email, message, and any photos will be shared with {kind==='quote'?'this shop':'DGD reviewers'}.</p><button className="primary" disabled={busy}>{busy?'Sending…':kind==='quote'?'Send quote request':'Send report'}</button><p role="status">{message}</p></form></section>;
}
export function Inbox(){const [rows,R]=useState<any[]>([]),[message,M]=useState('Loading inbox…');useEffect(()=>{headers().then(h=>fetch('/api/shop-finder/messages',{headers:h})).then(r=>r.json()).then(d=>{R(d.messages||[]);M(d.error||(!d.messages?.length?'No requests or reports yet.':''));}).catch(()=>M('Inbox unavailable. Please try again.'));},[]);return <section className="form-card"><h2>Requests & reports</h2><p role="status">{message}</p>{rows.map(r=><article key={r.id} className="shop-card"><div><h3>{r.directory_shops?.name} · {r.kind==='quote'?'Quote request':'Listing report'}</h3><p style={{whiteSpace:'pre-wrap'}}>{r.body}</p><div className="grid3">{(r.photos||[]).map((photo:string,i:number)=><img src={photo} key={i} alt="Customer project" style={{maxWidth:"100%"}}/>)}</div><a href={`mailto:${r.email}`}>Reply to {r.email}</a><p className="small">{new Date(r.created_at).toLocaleString()}</p></div></article>)}</section>}
